name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VCPKG_ROOT: /usr/local/share/vcpkg

jobs:
  build:

    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: brew install autoconf automake autoconf-archive libtool
      #- run: vcpkg install boost:arm64-osx
      - run: vcpkg install python3:arm64-osx -v 3.11.1
      - run: mkdir build
      - run: cmake -B build
      - run: cmake --build build
      # - run: ./build/simple_executable
      - run: file ./build/simple_executable
      - uses: actions/upload-artifact@v4
        with:
          name: simple_executable
          path: ./build/simple_executable
