name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - run: uname -a
    - run: brew install autoconf automake autoconf-archive libtool
    - run: ls $VCPKG_ROOT
    - run: mkdir build
    - run: cmake -B build
    - run: cmake --build build
    - run: ./build/simple_executable
    - run: vcpkg install boost:arm64-osx
